vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.swapfile = false
vim.opt.hlsearch = false
vim.opt.showmode = false
vim.opt.backup = false
vim.opt.undodir = vim.env.HOME .. "/.cache/vim/undodir"
vim.opt.undofile = true
vim.opt.incsearch = true
vim.opt.scrolloff = 8
vim.opt.colorcolumn = "80"
vim.opt.completeopt = { "menuone", "noinsert", "noselect" }
vim.opt.cmdheight = 2
vim.opt.updatetime = 50
vim.opt.shortmess:append("c")
vim.opt.termguicolors = true
